### ISSUE TITLE
version of keras

### ISSUE THREAD

**Issue by Jiakui** [jacobssy/Traffic_Sign_detection#5]
Hi,

I tried to run predict.py  in detection folder with either  keras 1 or keras 2, but none would work due to import problems.  

What's the exact version of Keras are you using?

Thanks!

**Comment by jacobssy** [comment]
@Jiakui  Hi, My keras version is keras 2.1.2

**Comment by Jiakui** [comment]
**I am using keras 2.1.2 now, but there are some errors during running predict.py in the detection folder: 

python predict.py  -c config.json  -w weights/yolov2_traffic_sign.h5  -f 0** 

```
> Using TensorFlow backend.
> 2018-06-27 11:18:14.965770: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> __________________________________________________________________________________________________
> Layer (type)                    Output Shape         Param #     Connected to                     
> ==================================================================================================
> input_1 (InputLayer)            (None, 416, 416, 3)  0                                            
> __________________________________________________________________________________________________
> model_1 (Model)                 (None, 13, 13, 1024) 15739760    input_1[0][0]                    
> __________________________________________________________________________________________________
> conv_output (Conv2D)            (None, 13, 13, 125)  128125      model_1[1][0]                    
> __________________________________________________________________________________________________
> reshape_1 (Reshape)             (None, 13, 13, 5, 25 0           conv_output[0][0]                
> __________________________________________________________________________________________________
> input_2 (InputLayer)            (None, 1, 1, 1, 50,  0                                            
> __________________________________________________________________________________________________
> lambda_1 (Lambda)               (None, 13, 13, 5, 25 0           reshape_1[0][0]                  
>                                                                  input_2[0][0]                    
> ==================================================================================================
> Total params: 15,867,885
> Trainable params: 15,861,773
> Non-trainable params: 6,112
> __________________________________________________________________________________________________
> Make the model costs:0.732246
> weights/yolov2_traffic_sign.h5
> Traceback (most recent call last):
>   File "predict.py", line 107, in <module>
>     _main_(args)
>   File "predict.py", line 60, in _main_
>     yolo.load_weights(weights_path)
>   File "/home/jiakui/rasaHQ/Traffic_Sign_detection/detection/frontend.py", line 282, in load_weights
>     self.model.load_weights(weight_path)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2622, in load_weights
>     load_weights_from_hdf5_group(f, self.layers)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 3141, in load_weights_from_hdf5_group
>     ' elements.')
> ValueError: Layer #0 (named "model_1" in the current model) was found to correspond to layer model_1 in the save file. However the new layer model_1 expects 40 weights, but the saved weights have 110 elements.
> 
```

**Comment by jacobssy** [comment]
@Jiakui  I Think your weight file not match the architecture used in config, if you do not update the config file , the "architecture" is "YoloTiny", However, your weight file is YoloV2, So you should update the architecture to YoloV2(maybe yolov2 ..I dont remember correctly, please check the code)
